@baseUrl = http://localhost:3001

### Create User
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Giovane Richard",
    "email": "giovanerichard@email.com",
    "password": "123456"
}

### Get All Users
GET {{baseUrl}}/users?page=1&limit=10