@baseUrl = http://localhost:3001

### Create Category
POST {{baseUrl}}/banner
Content-Type: application/json

{
  "name": "Informática",
  "slug": "info"
}

### Get All Categories
GET {{baseUrl}}/banner?page=1&limit=10

### Get banner by Id
GET {{baseUrl}}/banner/2fbf95fa-df03-4343-9965-f864dd2b97ad

### Get banner by Slug
GET {{baseUrl}}/banner/info/metadata

### Updated banner
PATCH {{baseUrl}}/banner/2fbf95fa-df03-4343-9965-f864dd2b97ad
Content-Type: application/json

{
  "name": "Informática básica"
}